# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: 1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='1.proto',
  package='test',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x07\x31.proto\x12\x04test\"0\n\x14get_suggestion_param\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x01 \x01(\t\"&\n\x14get_suggestion_reply\x12\x0e\n\x06result\x18\x01 \x01(\t2X\n\nbo_advisor\x12J\n\x0eget_suggestion\x12\x1a.test.get_suggestion_param\x1a\x1a.test.get_suggestion_reply\"\x00\x62\x06proto3'
)




_GET_SUGGESTION_PARAM = _descriptor.Descriptor(
  name='get_suggestion_param',
  full_name='test.get_suggestion_param',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='test.get_suggestion_param.id', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='test.get_suggestion_param.name', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=65,
)


_GET_SUGGESTION_REPLY = _descriptor.Descriptor(
  name='get_suggestion_reply',
  full_name='test.get_suggestion_reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='test.get_suggestion_reply.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=105,
)

DESCRIPTOR.message_types_by_name['get_suggestion_param'] = _GET_SUGGESTION_PARAM
DESCRIPTOR.message_types_by_name['get_suggestion_reply'] = _GET_SUGGESTION_REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

get_suggestion_param = _reflection.GeneratedProtocolMessageType('get_suggestion_param', (_message.Message,), {
  'DESCRIPTOR' : _GET_SUGGESTION_PARAM,
  '__module__' : '1_pb2'
  # @@protoc_insertion_point(class_scope:test.get_suggestion_param)
  })
_sym_db.RegisterMessage(get_suggestion_param)

get_suggestion_reply = _reflection.GeneratedProtocolMessageType('get_suggestion_reply', (_message.Message,), {
  'DESCRIPTOR' : _GET_SUGGESTION_REPLY,
  '__module__' : '1_pb2'
  # @@protoc_insertion_point(class_scope:test.get_suggestion_reply)
  })
_sym_db.RegisterMessage(get_suggestion_reply)



_BO_ADVISOR = _descriptor.ServiceDescriptor(
  name='bo_advisor',
  full_name='test.bo_advisor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=107,
  serialized_end=195,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_suggestion',
    full_name='test.bo_advisor.get_suggestion',
    index=0,
    containing_service=None,
    input_type=_GET_SUGGESTION_PARAM,
    output_type=_GET_SUGGESTION_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BO_ADVISOR)

DESCRIPTOR.services_by_name['bo_advisor'] = _BO_ADVISOR

# @@protoc_insertion_point(module_scope)
