# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import 1_pb2 as 1__pb2


class bo_advisorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_suggestion = channel.unary_unary(
                '/test.bo_advisor/get_suggestion',
                request_serializer=1__pb2.get_suggestion_param.SerializeToString,
                response_deserializer=1__pb2.get_suggestion_reply.FromString,
                )


class bo_advisorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_suggestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_bo_advisorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_suggestion': grpc.unary_unary_rpc_method_handler(
                    servicer.get_suggestion,
                    request_deserializer=1__pb2.get_suggestion_param.FromString,
                    response_serializer=1__pb2.get_suggestion_reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'test.bo_advisor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class bo_advisor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_suggestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/test.bo_advisor/get_suggestion',
            1__pb2.get_suggestion_param.SerializeToString,
            1__pb2.get_suggestion_reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
