# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import my_rpc.DemoAdvisor_pb2 as DemoAdvisor__pb2


class DemoAdvisorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_suggestion = channel.unary_unary(
                '/test_1.DemoAdvisor/get_suggestion',
                request_serializer=DemoAdvisor__pb2.get_suggestion_param.SerializeToString,
                response_deserializer=DemoAdvisor__pb2.get_suggestion_reply.FromString,
                )
        self.update_observation = channel.unary_unary(
                '/test_1.DemoAdvisor/update_observation',
                request_serializer=DemoAdvisor__pb2.update_observation_param.SerializeToString,
                response_deserializer=DemoAdvisor__pb2.update_observation_reply.FromString,
                )


class DemoAdvisorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_suggestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_observation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DemoAdvisorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_suggestion': grpc.unary_unary_rpc_method_handler(
                    servicer.get_suggestion,
                    request_deserializer=DemoAdvisor__pb2.get_suggestion_param.FromString,
                    response_serializer=DemoAdvisor__pb2.get_suggestion_reply.SerializeToString,
            ),
            'update_observation': grpc.unary_unary_rpc_method_handler(
                    servicer.update_observation,
                    request_deserializer=DemoAdvisor__pb2.update_observation_param.FromString,
                    response_serializer=DemoAdvisor__pb2.update_observation_reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'test_1.DemoAdvisor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DemoAdvisor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_suggestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/test_1.DemoAdvisor/get_suggestion',
            DemoAdvisor__pb2.get_suggestion_param.SerializeToString,
            DemoAdvisor__pb2.get_suggestion_reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update_observation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/test_1.DemoAdvisor/update_observation',
            DemoAdvisor__pb2.update_observation_param.SerializeToString,
            DemoAdvisor__pb2.update_observation_reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
