# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DemoAdvisor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DemoAdvisor.proto',
  package='test_1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x44\x65moAdvisor.proto\x12\x06test_1\"+\n\x14get_suggestion_param\x12\x13\n\x0bquestion_id\x18\x01 \x01(\x05\"&\n\x14get_suggestion_reply\x12\x0e\n\x06result\x18\x01 \x01(\t\"<\n\x18update_observation_param\x12\x0e\n\x06new_id\x18\x01 \x01(\x05\x12\x10\n\x08new_name\x18\x02 \x01(\t\",\n\x18update_observation_reply\x12\x10\n\x08log_info\x18\x01 \x01(\t2\xb9\x01\n\x0b\x44\x65moAdvisor\x12N\n\x0eget_suggestion\x12\x1c.test_1.get_suggestion_param\x1a\x1c.test_1.get_suggestion_reply\"\x00\x12Z\n\x12update_observation\x12 .test_1.update_observation_param\x1a .test_1.update_observation_reply\"\x00\x62\x06proto3'
)




_GET_SUGGESTION_PARAM = _descriptor.Descriptor(
  name='get_suggestion_param',
  full_name='test_1.get_suggestion_param',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='question_id', full_name='test_1.get_suggestion_param.question_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=72,
)


_GET_SUGGESTION_REPLY = _descriptor.Descriptor(
  name='get_suggestion_reply',
  full_name='test_1.get_suggestion_reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='test_1.get_suggestion_reply.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=112,
)


_UPDATE_OBSERVATION_PARAM = _descriptor.Descriptor(
  name='update_observation_param',
  full_name='test_1.update_observation_param',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='new_id', full_name='test_1.update_observation_param.new_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='new_name', full_name='test_1.update_observation_param.new_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=174,
)


_UPDATE_OBSERVATION_REPLY = _descriptor.Descriptor(
  name='update_observation_reply',
  full_name='test_1.update_observation_reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='log_info', full_name='test_1.update_observation_reply.log_info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=220,
)

DESCRIPTOR.message_types_by_name['get_suggestion_param'] = _GET_SUGGESTION_PARAM
DESCRIPTOR.message_types_by_name['get_suggestion_reply'] = _GET_SUGGESTION_REPLY
DESCRIPTOR.message_types_by_name['update_observation_param'] = _UPDATE_OBSERVATION_PARAM
DESCRIPTOR.message_types_by_name['update_observation_reply'] = _UPDATE_OBSERVATION_REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

get_suggestion_param = _reflection.GeneratedProtocolMessageType('get_suggestion_param', (_message.Message,), {
  'DESCRIPTOR' : _GET_SUGGESTION_PARAM,
  '__module__' : 'DemoAdvisor_pb2'
  # @@protoc_insertion_point(class_scope:test_1.get_suggestion_param)
  })
_sym_db.RegisterMessage(get_suggestion_param)

get_suggestion_reply = _reflection.GeneratedProtocolMessageType('get_suggestion_reply', (_message.Message,), {
  'DESCRIPTOR' : _GET_SUGGESTION_REPLY,
  '__module__' : 'DemoAdvisor_pb2'
  # @@protoc_insertion_point(class_scope:test_1.get_suggestion_reply)
  })
_sym_db.RegisterMessage(get_suggestion_reply)

update_observation_param = _reflection.GeneratedProtocolMessageType('update_observation_param', (_message.Message,), {
  'DESCRIPTOR' : _UPDATE_OBSERVATION_PARAM,
  '__module__' : 'DemoAdvisor_pb2'
  # @@protoc_insertion_point(class_scope:test_1.update_observation_param)
  })
_sym_db.RegisterMessage(update_observation_param)

update_observation_reply = _reflection.GeneratedProtocolMessageType('update_observation_reply', (_message.Message,), {
  'DESCRIPTOR' : _UPDATE_OBSERVATION_REPLY,
  '__module__' : 'DemoAdvisor_pb2'
  # @@protoc_insertion_point(class_scope:test_1.update_observation_reply)
  })
_sym_db.RegisterMessage(update_observation_reply)



_DEMOADVISOR = _descriptor.ServiceDescriptor(
  name='DemoAdvisor',
  full_name='test_1.DemoAdvisor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=223,
  serialized_end=408,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_suggestion',
    full_name='test_1.DemoAdvisor.get_suggestion',
    index=0,
    containing_service=None,
    input_type=_GET_SUGGESTION_PARAM,
    output_type=_GET_SUGGESTION_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='update_observation',
    full_name='test_1.DemoAdvisor.update_observation',
    index=1,
    containing_service=None,
    input_type=_UPDATE_OBSERVATION_PARAM,
    output_type=_UPDATE_OBSERVATION_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEMOADVISOR)

DESCRIPTOR.services_by_name['DemoAdvisor'] = _DEMOADVISOR

# @@protoc_insertion_point(module_scope)
